baseURL = "/"
relativeURLs = true

languageCode = 'en-us'
title = 'PhantomAfrica'
theme = "archie"
copyright = "©  Qiutong"

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page
hasCJKLanguage = "true" 
summaryLength =200

disableHugoGeneratorInject = "true"
enableRobotsTXT = true
DefaultContentLanguage = 'zh-cn'

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "憤怒與神秘"

	

[[params.social]]
name = "Telegram"
icon = "send"
url = "https://t.me/PhantomAfrica"

[[params.social]]
name = "Mail"
icon = "mail"
url = "mailto:qiu@ik.me"

[[menu.main]]
name = "COLOPHON"
url = "/colophon"
weight = 1

[[menu.main]]
name = "ARCHIVE"
url = "/posts"
weight = 2

[[menu.main]]
name = "PROJECT"
url = "/project"
weight = 3
